import type { Metadata } from "next";
import localFont from "next/font/local";
import SideNav from "./ui/side-nav";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex justify-center`}
      >
        <main className="flex w-full">
          <nav className="navigation w-1/12 p-0 pt-4 lg:w-1/4 lg:p-4">
            <div className="site-header text-center lg:text-left w-full">
              <h2 className="text-sm lg:text-3xl">Drizzle</h2>
            </div>
            <SideNav />
          </nav>
          <div className="w-11/12 lg:w-3/4 p-4">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
